package com.yatu.electronicCigarettesShop.dto;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.ForeignKey;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

// Generated Sep 6, 2019, 11:54:58 PM by Hibernate Tools 5.2.12.Final

/**
 * OrderDetails generated by hbm2java
 */
@Entity
@Table(name = "order_detail")
public class OrderDetailDTO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7550745928843183535L;
	private int id;
	private double amount;
	private double price;
	private int quantity;
	private OrderDTO order;
	private ProductDTO product;

	public OrderDetailDTO() {
	}

	public OrderDetailDTO(int id, double amount, double price, int quantity, OrderDTO orderId, ProductDTO productId) {
		this.id = id;
		this.amount = amount;
		this.price = price;
		this.quantity = quantity;
		this.order = orderId;
		this.product = productId;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", length = 11, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "amount", nullable = false)
	public double getAmount() {
		return this.amount;
	}

	public void setAmount(double amount) {
		this.amount = amount;
	}

	@Column(name = "price", nullable = false)
	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "order_id", nullable = false,
    foreignKey = @ForeignKey(name = "fk_ORDER_DETAIL_ORD") )
	public OrderDTO getOrder() {
		return this.order;
	}

	public void setOrder(OrderDTO orderId) {
		this.order = orderId;
	}

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "product_id", nullable = false,
    foreignKey = @ForeignKey(name = "fk_ORDER_DETAIL_PROD") )
	public ProductDTO getProduct() {
		return this.product;
	}

	public void setProduct(ProductDTO productId) {
		this.product = productId;
	}
	
}
