package com.yatu.electronicCigarettesShop.dto;
// Generated Aug 23, 2019, 11:49:59 PM by Hibernate Tools 5.2.12.Final

import java.util.Arrays;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name="product")
public class ProductDTO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8073250400861393119L;
	private int id;
	private Date createDate;
	private byte[] image;
	private String name;
	private double price;

	public ProductDTO() {
	}

	public ProductDTO(int id, Date createDate, String name, double price) {
		this.id = id;
		this.createDate = createDate;
		this.name = name;
		this.price = price;
	}

	public ProductDTO(int id, Date createDate, byte[] image, String name, double price) {
		this.id = id;
		this.createDate = createDate;
		this.image = image;
		this.name = name;
		this.price = price;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", length = 11, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_date", nullable = false)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

    @Lob
    @Column(name = "image", length = Integer.MAX_VALUE, nullable = true)
	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	@Column(name = "name", length = 255, nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "price", nullable = false)
	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

}
